language: go
before_install:
- sudo apt-get update
- sudo apt-get install nodejs -y
install:
- go get ./...
- cd web && npm install && npm run build
script:
- cd $TRAVIS_BUILD_DIR && go test ./...
- cd web && npm run lint
after_success:
- if [ -z $TRAVIS_TAG ]; then echo "skipped building artifacts."; else cd $TRAVIS_BUILD_DIR && scripts/build-dist $TRAVIS_TAG; fi
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  file:
  - artifacts/koala-*.tar.gz
  on:
    tags: true
  api_key:
    secure: Pm3ZghHb7AjyyRBxs9jZCkCznPN4fui7HctFOS+F+E92JZOZobixWIzZeq7gliXe/b+6zDNJeLDoEk+FEi89eKsf+2RpRBjEyDiO3ptboQ7pzy8SzChoiftleiTrCjLfM+gjskMVJsfagMwlr6G7DjVoP48B/RsHoYs58xMcSmnnH6BLKX+HYFuCT82sYYIQrfFdz6wIhAo8WvEEL85UtE3bARUAZVlxKCpQ03S/Xp9J26i9QWAgymzkm3KBex16SfzNsyKQtTMFbseDQnsYKNC8G8wEo5Qy0rSH4hCwysCGQMSHcMS0APOGGKpbOIhuEjlAprJuscRx60h0fa9U4B/m6qYqcXEVhHPhCmD93b7k/4uBc6YLVa1h5uVK/w+tsWozxc66Tjt3Dc62MyfjcT36PwsosAu/OUwexQdhSDZIe5Ey1dWtIeWFVd137+v2x98fvD5Mvv+A2f3RNzkkoGJVCpkK++8OyETPr72sUokKOnmk7yrNEC8Jdr8K65W0dVcXFZ3QOqKfKQF6Lee9jK/F+kQxS8X2ETd81XGyGOV0FKR9QmCMSvM1/hNlVblYezSmEoBgoBZM6h+U6mYNQHJ+J415ay4hOWTny2ue1KT8XAj/ytqk5fGLrTRY1XvvWS+4xlFPnmmo3qBC/M+QBL0gDte6LwVd3uGUs2SLmzk=