#!/bin/bash
set +x;

function makedist {
    printf "Building %-14s ..." "$1-$2"
    GOOS=$1 GOARCH=$2 go build -o koala/koala -ldflags "-X main.version=$3" cmd/koala/main.go
    tar czf artifacts/koala-$3-$1-$2.tar.gz koala/
    rm koala/koala
    printf " done.\n"
}

if [ "$1" == "" ]
then
    printf "USAGE: %s [version]\n" $0
    exit 1
fi


printf "Generating artifacts for koala %s ...\n" $1
mkdir -p koala artifacts
cp -r web/dist koala/web

platforms="linux:amd64,arm darwin:amd64"
for pfs in $(echo $platforms | tr " " "\n")
do
    params=$(echo $pfs | tr ":" "\n")
    goos=$(echo $params | awk '{print $1}')
    archs=$(echo $params | awk '{print $2}' | tr "," "\n")
    for goarch in $archs
    do
        makedist $goos $goarch $1
    done
done

rm -rf koala
printf "done."